
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/graphql_demo
        username: postgres
        password: 1705
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    graphql:
        graphiql:
            enabled: true